### ISSUE TITLE
Make Request::payload and Request::signature protected

### ISSUE THREAD

**Issue by jwpage** [philipbrown/signature-php#14]
Just thought I'd gauge your opinion on this one before I go and make a pull request.

Seems to me like `Request::payload()` and `Request::signature()` methods should both be private or (or protected). The example in the docs is something like:

```php
$request = new Request('GET', 'users');
$request->sign(new Token('foo', 'bar'));
```

Since payload and signature methods aren't referenced here, they seem to be internal implementation details that the end-user of Signature shouldn't need to know about.

The "real" public API is the constructor, and the sign method.

Making these internal functions public will simplify testing and means fewer BC breaks since there'll be fewer public methods, thus allowing for greater freedom during refactoring.

Obviously this'll be another (sorry) BC break, if I turn this into a PR, bumping the release to 5.0.0. If you're on board, I'm happy to make a pull request for it. :+1:

**Comment by philipbrown** [comment]
Sure, that sounds good to me! To be honest I'm usually pretty aggressive with minimising the public API, not sure why I didn't already do that to be honest.

Thank you :+1:
