### ISSUE TITLE
array_change_key_case not working

### ISSUE THREAD

**Issue by afibanez** [philipbrown/signature-php#21]
In function:

private function payload(array $auth, array $params)
    {
        $payload = array_merge($auth, $params);
        array_change_key_case($payload, CASE_LOWER);
        ksort($payload);
        return $payload;
    }

array_change_key_case is doing nothing, because this function don't update the array inplace, returns a copy: http://php.net/manual/en/function.array-change-key-case.php

**Comment by jwpage** [comment]
Since this is changing the payload the  Request::VERSION constant should have been bumped as well. Not a big issue, but worth noting.

**Comment by philipbrown** [comment]
Argh, I always forget to do that. Thank you :)
