### ISSUE TITLE
HHVM build failing

### ISSUE THREAD

**Issue by jwpage** [philipbrown/signature-php#22]
Travis shows the latest build as failing: https://travis-ci.org/philipbrown/signature-php/jobs/60657483

Looks like this was an issue in [HHVM/PHPUnit](https://github.com/sebastianbergmann/phpunit/issues/1684), which is now fixed. I think all you'll have to do is manually hit "Restart Build" in Travis, and it should pull down the latest version of PHPUnit and pass.

Can you give it a shot for me? :smile:

**Comment by philipbrown** [comment]
Thank you sir :smile:
