### ISSUE TITLE
Lower Case Keys

### ISSUE THREAD

**Issue by michaeljs1990** [philipbrown/signature-php#24]
in this line right here you are setting all keys to be lower case https://github.com/philipbrown/signature-php/blob/master/src/Request.php#L79. Is this part of the HMAC spec or any reason it was done this way? Ran into some issues when generating a signature in another language and tracked the issue down to a param called "aThing".

**Comment by jwpage** [comment]
Out of interest, what other language/lib were you using to generate the signature?

**Comment by michaeljs1990** [comment]
This was in ruby using a custom implementation.

**Comment by philipbrown** [comment]
No particular reason I just copied the Ruby implementation https://github.com/mloughran/signature/blob/master/lib/signature.rb#L35

**Comment by michaeljs1990** [comment]
Interesting. I was looking over the HMAC spec and it doesn't specify case in any place unfortunately which is a little sad since I can see this being implemented differently from language to language and lib to lib.
