### ISSUE TITLE
Token $token param

### ISSUE THREAD

**Issue by Alphapixels** [philipbrown/signature-php#8]
What is this parameter for? The lack of documentation is making the use of the library hell. No offense.

**Comment by philipbrown** [comment]
`Token $token` is the Value Object that holds the `key` and the `secret`.

Which bit are you struggling with?

**Comment by Alphapixels** [comment]
In the documentation there was no mention of having to pass the key/secret, they were in the incorrect order, I solved it by putting the token before.
